global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'server'
    static_configs:
      - targets: ['imgboard:9091']
    metrics_path: /metrics

  - job_name: 'preprocessor'
    static_configs:
      - targets: ['imgboard:9092']
    metrics_path: /metrics
